apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: node_aug_twelve 
  janus-idp.io/tekton: node_aug_twelve
  backstage.io/kubernetes-id: node_aug_twelve
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: node_aug_twelve
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  