apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: node_aug_twelve
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node_aug_twelve 
  name: node_aug_twelve
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: node_aug_twelve 
